# Generated by Django 4.2.1 on 2023-06-03 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('apellido', models.CharField(max_length=140)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, unique=True)),
                ('numero_celular', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=140)),
                ('antecedente_medico', models.TextField(max_length=140, null=True)),
                ('contacto_emergencia', models.CharField(max_length=10, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('apellido', models.CharField(max_length=140)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, unique=True)),
                ('numero_celular', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=140)),
                ('titulo_universitario', models.CharField(max_length=140, null=True)),
                ('especialidad', models.CharField(max_length=140, null=True)),
                ('genero', models.CharField(max_length=100)),
                ('area_estudio', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('fecha_nacimiento', models.DateField()),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('apellido', models.CharField(max_length=140)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, unique=True)),
                ('numero_celular', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=140)),
                ('titulo_universitario', models.CharField(max_length=140, null=True)),
                ('especialidad', models.CharField(max_length=140, null=True)),
                ('identificacion', models.CharField(max_length=10, unique=True)),
                ('area_operacion', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('fecha_nacimiento', models.DateField()),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
