# Generated by Django 4.2.1 on 2023-06-09 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0002_paciente_usuariocomun_usuariotecnico_delete_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=80, null=True)),
                ('num_test', models.IntegerField()),
                ('grado_dificultad', models.CharField(max_length=80, null=True)),
                ('descripcion_categoria', models.TextField(max_length=50, null=True)),
                ('fecha_registro_categoria', models.DateField(auto_now=True)),
                ('estado_categoria', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('identificador_contenido', models.IntegerField(unique=True)),
                ('contenido', models.CharField(max_length=80, null=True)),
                ('dominio', models.CharField(max_length=80, null=True)),
                ('fecha_registro_contenido', models.DateField(auto_now=True)),
                ('estado_contenido', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=80, null=True, unique=True)),
                ('descripcion_curso', models.TextField(max_length=50, null=True)),
                ('estado_curso', models.BooleanField(default=True)),
                ('fecha_registro_curso', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradoTDAH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel', models.CharField(max_length=80, null=True, unique=True)),
                ('numero_categorias', models.IntegerField()),
                ('grado_dificultad', models.CharField(max_length=80, null=True)),
                ('descripcion_grado', models.CharField(max_length=80, null=True)),
                ('fecha_registro_grado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_peticion', models.BooleanField(default=False)),
                ('fecha_registro_peticion', models.DateField(auto_now=True)),
                ('motivo_peticion', models.TextField()),
                ('peticion', models.TextField(blank=True, max_length=50, null=True)),
                ('tipo_peticion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_registro_reporte', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotaciones', models.TextField(blank=True, max_length=50, null=True)),
                ('calificacion', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_registro_resultado', models.DateField(auto_now=True)),
                ('fecha_edit_resultado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotaciones', models.TextField()),
                ('fecha_registro_sala', models.DateField(auto_now=True)),
                ('estado_sala', models.BooleanField(default=True)),
                ('cancelada_sala', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='DetalleContenidoResuleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resolver', models.DateField(default=None)),
                ('puntuacion', models.CharField(max_length=80, null=True)),
                ('resultado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='APPWapiptdah.resultados')),
            ],
        ),
    ]
