# Generated by Django 4.2.2 on 2023-06-19 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0003_categoria_contenido_curso_gradotdah_peticion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradotdah',
            name='usuario_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grados_tdah', to='APPWapiptdah.usuariotecnico'),
        ),
        migrations.AddField(
            model_name='usuariocomun',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuariotecnico',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
