# Generated by Django 4.2.2 on 2023-06-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0004_gradotdah_usuario_tecnico_usuariocomun_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='antecedente_medico',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='usuariocomun',
            name='titulo_universitario',
        ),
        migrations.RemoveField(
            model_name='usuariotecnico',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuariotecnico',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='usuariotecnico',
            name='titulo_universitario',
        ),
    ]
