# Generated by Django 4.2.2 on 2023-06-22 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0006_remove_paciente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='usuario_comun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='APPWapiptdah.usuariocomun'),
        ),
    ]
