# Generated by Django 4.2.2 on 2023-06-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0008_categoria_grado_tdah_f_categoria_slug_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradotdah',
            name='slug_grado',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
