# Generated by Django 4.2.2 on 2023-06-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0009_gradotdah_slug_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug_curso',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
