# Generated by Django 4.2.2 on 2023-06-26 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0010_curso_slug_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos', to='APPWapiptdah.categoria'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='slug_contenido',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
