# Generated by Django 4.2.2 on 2023-07-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0012_peticion_slug_peticion_peticion_usuario_comun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='is_paciente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariocomun',
            name='is_usuario_comun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariotecnico',
            name='is_usuario_tecnico',
            field=models.BooleanField(default=True),
        ),
    ]
