# Generated by Django 4.2.2 on 2023-07-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APPWapiptdah', '0013_paciente_is_paciente_usuariocomun_is_usuario_comun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePacienteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_detalle', models.BooleanField(default=True)),
                ('fecha_registro_detalle', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso', to='APPWapiptdah.curso')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='APPWapiptdah.paciente')),
            ],
        ),
    ]
